### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by Spottie97** [Spottie97/CodeForte-----React-Assessment#1]
Continue debugging this error 👍🏻 

Uncaught TypeError: Cannot read properties of undefined (reading 'items')
    at checkout.js:8:1
    at memoizedSelector (with-selector.development.js:79:1)
    at getSnapshotWithSelector (with-selector.development.js:134:1)
    at mountSyncExternalStore (react-dom.development.js:16799:1)
    at Object.useSyncExternalStore (react-dom.development.js:17727:1)
    at useSyncExternalStore (react.development.js:1676:1)
    at useSyncExternalStoreWithSelector (with-selector.development.js:145:1)
    at useSelector (useSelector.js:41:1)
    at Checkout (checkout.js:8:1)

Its in line 8.

**Comment by Spottie97** [comment]
The issue for this error was due to the way we handle our cart using the cart.js function.
By modifying this line to include the array that sets it to null at the start.

const cartItems = useSelector((state) => state.items) || [];

To fix it you need to ensure that the array is set to null
